$(document).ready(function() {     
        $('.RB').hover(function(){     
            $('.RBoverlap').addClass('RBoverlaphover');    
        },     
        function(){    
            $('.RBoverlap').removeClass('RBoverlaphover');     
        });
        $('.Portfolio').hover(function(){     
            $('.Portfoliooverlap').addClass('Portfoliooverlaphover');    
        },     
        function(){    
            $('.Portfoliooverlap').removeClass('Portfoliooverlaphover');     
        });
        $('.Fonts').hover(function(){     
            $('.Fontsoverlap').addClass('Fontsoverlaphover');    
        },     
        function(){    
            $('.Fontsoverlap').removeClass('Fontsoverlaphover');     
        });
    });  